#ifndef _TIMINGS_H_
#define _TIMINGS_H_

#define UPDATE_LCD_DELAY 4
#define UPDATE_LCD_PERIOD 1000

#define MOISTURE_DELAY 0
#define MOISTURE_PERIOD 50

#define LIGHT_DELAY 1
#define LIGHT_PERIOD 50

#define TEMP_DELAY 2
#define TEMP_PERIOD 50

#define DATA_DELAY 2000
#define DATA_PERIOD 20000

#endif
